### ISSUE TITLE
First things todo

### ISSUE THREAD

**Issue by thanasipantazides** [foxsi/foxsi4-commands#1]
### Todo

- [x] Write .csv (manually) based on Drive command deck spreadsheet. Should capture all commands (name and hex code), command translation (memory address, length, reply length), and metadata (flight use, targets, initiators, description).
- [x] Write .csv (manually) based on `all_systems.json` ([in the GSE repository](https://github.com/foxsi/GSE-FOXSI-4/blob/0e56023e45872cb512f451244addf14a2f742a4b/config/all_systems.json)) to use as reference for valid systems.
- [x] Write .py script that ingests the .csv deck, validates commands, guarantee command uniqueness, then:
- [x] generate a Python file that makes a (hardcoded) `Dict` for each detector's commands,
- [x] generate a C++ header that instantiates a (hardcoded) `std::map` for each detector's commands, and
- [x] generate a .json file capturing the .csv contents for all commands.
- [ ] Commits that change the deck or system list should be carefully vetted. Set up testing or something.
- [x] Detector providers can then edit address and length info in the source .csv file, then rerun the script to generate `Dict`s, `std::map`s etc.
- [x] Add access/modification info to `README.md`.
